services:
  backend:
    build: .
    image: aerolens-portal-backend:latest
    container_name: aerolens-portal-backend
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=ap-south-1
      - SECRET_NAME=/myapp/prod/env
    restart: always
