services:
  backend-dev:
    build: .
    image: aerolens-portal-backend-dev:latest
    container_name: aerolens-portal-backend-dev
    ports:
      - "3001:3000"
    environment:
      - AWS_REGION=ap-south-1
      - SECRET_NAME=dev/myapp/secrets
    restart: always
